#include <iostream> //  ÷„Ì‰ „ﬂ »… «·≈œŒ«· Ê«·≈Œ—«Ã «·√”«”Ì…
#include "clsMyStack.h" //  ÷„Ì‰ „·› «·—√” «·Œ«’ »«·ﬂÊ„…

using namespace std; // «” Œœ«„ ›÷«¡ «·√”„«¡ std · Ã‰» ﬂ «»… std:: ﬁ»· ﬂ· «” Œœ«„ ·œÊ«· √Ê ﬂ«∆‰«  „‰ „ﬂ »… «·ﬁÌ«”Ì…

int main()
{
    clsMyStack<int> MyStack; // ≈‰‘«¡ ﬂ«∆‰ „‰ ‰Ê⁄ clsMyStack · Œ“Ì‰ √⁄œ«œ ’ÕÌÕ…

    MyStack.push(10); // ≈÷«›… «·—ﬁ„ 10 ≈·Ï «·ﬂÊ„…
    MyStack.push(20); // ≈÷«›… «·—ﬁ„ 20 ≈·Ï «·ﬂÊ„…
    MyStack.push(30); // ≈÷«›… «·—ﬁ„ 30 ≈·Ï «·ﬂÊ„…
    MyStack.push(40); // ≈÷«›… «·—ﬁ„ 40 ≈·Ï «·ﬂÊ„…
    MyStack.push(50); // ≈÷«›… «·—ﬁ„ 50 ≈·Ï «·ﬂÊ„…

    cout << "\nStack: \n";
    MyStack.Print(); // ÿ»«⁄… „Õ ÊÌ«  «·ﬂÊ„…

    cout << "\nStack Size: " << MyStack.Size(); // ÿ»«⁄… ÕÃ„ «·ﬂÊ„…
    cout << "\nStack Top: " << MyStack.Top(); // ÿ»«⁄… «·⁄‰’— ›Ì ﬁ„… «·ﬂÊ„…
    cout << "\nStack Bottom: " << MyStack.Bottom(); // ÿ»«⁄… «·⁄‰’— ›Ì ﬁ«⁄ «·ﬂÊ„…

    MyStack.pop(); // ≈“«·… «·⁄‰’— ›Ì ﬁ„… «·ﬂÊ„…

    cout << "\n\nStack after pop() : \n";
    MyStack.Print(); // ÿ»«⁄… „Õ ÊÌ«  «·ﬂÊ„… »⁄œ ⁄„·Ì… «·≈“«·…

    // «· „œÌœ #1: ÿ»«⁄… «·⁄‰’— ›Ì «·›Â—” 2
    cout << "\n\n Item(2) : " << MyStack.GetItem(2);

    // «· „œÌœ #2: ⁄ﬂ”  — Ì» «·ﬂÊ„…
    MyStack.Reverse();
    cout << "\n\nStack after reverse() : \n";
    MyStack.Print();

    // «· „œÌœ #3:  ÕœÌÀ «·⁄‰’— ›Ì «·›Â—” 2 »«·ﬁÌ„… 600
    MyStack.UpdateItem(2, 600);
    cout << "\n\nStack after updating Item(2) to 600 : \n";
    MyStack.Print();

    // «· „œÌœ #4: ≈œ—«Ã «·ﬁÌ„… 800 »⁄œ «·⁄‰’— ›Ì «·›Â—” 2
    MyStack.InsertAfter(2, 800);
    cout << "\n\nStack after Inserting 800 after Item(2) : \n";
    MyStack.Print();

    // «· „œÌœ #5: ≈œ—«Ã «·ﬁÌ„… 1000 ›Ì ﬁ„… «·ﬂÊ„…
    MyStack.InsertAtFront(1000);
    cout << "\n\nStack after Inserting 1000 at top: \n";
    MyStack.Print();

    // «· „œÌœ #6: ≈œ—«Ã «·ﬁÌ„… 2000 ›Ì ﬁ«⁄ «·ﬂÊ„…
    MyStack.InsertAtBack(2000);
    cout << "\n\nStack after Inserting 2000 at bottom: \n";
    MyStack.Print();

    // «· „œÌœ #7: „”Õ Ã„Ì⁄ «·⁄‰«’— „‰ «·ﬂÊ„…
    MyStack.Clear();
    cout << "\n\nStack after Clear(): \n";
    MyStack.Print();

    system("pause>0"); // «‰ Ÿ«— «·„” Œœ„ ··÷€ÿ ⁄·Ï “— ·≈‰Â«¡ «·»—‰«„Ã
}
